

#include "nsISupports.idl"

[scriptable, uuid(5d2f9400-41c8-11e2-a25f-0800200c9a66)]
interface nsITabulationHandler : nsISupports
{
  bool getWhenToOpenTabs();

  string setOpenTabsEveryTime();
  string setShowOpenAllTime();
  string setShowClosedAllTime();
  string setShowSwitchedAllTime();
  string clearHistory();
  string test(); 
  void startup();
  void shutdown();
  void observe();
  
};  
